services:
  - type: web
    name: crimescope-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 180 --workers 1 --chdir backend app:app
